title: Artist Hamed Gebril
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0.5
  rhythmicContrast: 0.5
  brandColors:
    - '#ffffff'
    - '#cfbfa8'
    - '#2c1412'
    - '#9f6535'
    - '#bd8d65'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Hamed Gebril
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.37646
layout_spectrum: 1
