name: Hamed Gebril
favicon: null
layout_spectrum: 0.51085
typography_spectrum: 0.37646
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#705544'
    - '#856e5f'
    - '#442918'
    - '#a18a7b'
    - '#3b1604'
  brandStrength: 0.0002265495713800192
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
